# Secretlint configuration file
# See https://github.com/ZichenYuan/secretlint for documentation

# Enable/disable specific rules
rules:
  OPENAI_API_KEY: true
  GITHUB_PAT: true
  AWS_ACCESS_KEY: true
  AWS_SECRET_KEY: true
  STRIPE_LIVE_PK: true
  STRIPE_LIVE_SK: true
  SLACK_TOKEN: true
  JWT_TOKEN: true
  GENERIC_API_KEY: true
  PRIVATE_KEY: true

# Global settings
settings:
  # Exit with code 1 when secrets are found (blocks commits)
  fail_on_detection: true
  
  # Show detailed output
  verbose: false
  
  # Minimum secret length to scan
  min_length: 10

# Custom patterns (future feature)
custom_rules: []
